# Generated by Django 3.2.16 on 2024-01-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='streettype',
            name='streettype_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('streettype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streettypes', to='addresses.streettype')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_num', models.CharField(max_length=50)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='addresses.locality')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='addresses.street')),
            ],
        ),
    ]
