# Generated by Django 3.2.16 on 2024-01-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20240124_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='addresses.locality'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='addresses.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='streettype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streets', to='addresses.streettype'),
        ),
    ]
